import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../sanity";
Header;
const Home: NextPage = (props) => {
  console.log(props);
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main></main>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const url = `
    *[_type == "post"]{
  _id,
  title,
  author->{
  name,image
},
body,
mainImage,
slug
}
    `;
  const posts = await sanityClient.fetch(url);

  return {
    props: { posts },
  };
};
